version: "3.9"

services:
  gateway-api:
    build:
      context: .
      target: development_stage
    volumes:
      - .:/app:cached
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DOCKER_BIND_MOUNT_IN_USE=true
      - INSTALL_PRECOMMIT=true
      - PARKING_PERMITS_GRAPHQL_API=http://graphql-api:8000
      - WAIT_FOR_PARKING_PERMITS_GRAPHQL_API=true

networks:
  default:
    name: helsinki
